### ISSUE TITLE
feat: support timestamps on archive.org

### ISSUE THREAD

**Issue by liliakai** [bellingcat/uniform-timezone#19]
Like these:

![Screenshot 2023-12-19 at 07 20 29](https://github.com/bellingcat/uniform-timezone/assets/1039940/cca326d7-b0bd-426d-952d-9a2911537dd4)

**Comment by liliakai** [comment]
These are in UTC already but would be handy to see them in local time.

**Comment by kishore881** [comment]
@msramalho raised PR #20 for this. could you pls take a look..?

**Comment by msramalho** [comment]
Merged PR and submitted v0.0.11 for review so it should be up on the store soon.
